
QUESTION_TEMPLATE = [
    "<image>\nPresent a compact description of the photo's key features.",
    "<image>\nGive a short and clear explanation of the subsequent image.",
    "<image>\nOffer a succinct explanation of the picture presented.",
    "<image>\nRender a clear and concise summary of the photo.",
    "<image>\nProvide a brief description of the given image.",
    "<image>\nRelay a brief, clear account of the picture shown.",
    "<image>\nPresent a compact description of the photo's key features.",
    "<image>\nWrite a terse but informative summary of the picture.",
    "<image>\nDescribe the image concisely.",
    "<image>\nShare a concise interpretation of the image provided.",
    "<image>\nGive a short and clear explanation of the subsequent image.",
    "<image>\nRelay a brief, clear account of the picture shown.",
    "<image>\nShare a concise interpretation of the image provided.",
    "<image>\nCreate a compact narrative representing the image presented.",
    "<image>\nRender a clear and concise summary of the photo.",
    "<image>\nCreate a compact narrative representing the image presented.",
    "<image>\nSummarize the visual content of the image.",
    "<image>\nDescribe the image concisely.",
    "<image>\nSummarize the visual content of the image.",
    "<image>\nOffer a succinct explanation of the picture presented.",
    "<image>\nWrite a terse but informative summary of the picture.",
    "<image>\nProvide a brief description of the given image.",
]

QUESTION_TEMPLATE_CHINESE = [
"<image>\n简要地描述照片的关键信息。",
"<image>\n简短明了地解释该图片。",
"<image>\n简要地解释所呈现的图片。",
"清晰简洁地总结照片。\n<image>",
"<image>\n简要描述这张图像。",
"简洁明了地描述所示图片。\n<image>",
"简要地描述照片的关键信息。\n<image>",
"<image>\n对图片进行简洁但信息丰富的总结。",
"<image>\n简要地描述图像。",
"<image>\n简洁地解释所提供的图像。",
"简短明了地解释这张图片。\n<image>",
"<image>\n简洁明了地描述所示图片。",
"简洁地解释这张图像。\n<image>",
"为该图像创建一个精简叙述。\n<image>",
"<image>\n清晰简洁地总结该照片。",
"<image>\n为该图像创建一个精简叙述。",
"<image>\n总结图像的视觉内容。",
"简洁地描述图像。\n<image>",
"总结图像的视觉内容。\n<image>",
"简洁地解释给定的图片。\n<image>",
"简单但信息丰富地总结图片。\n<image>",
"简要描述给定的图像。\n<image>",
]
